spring.application.name=DigitalBanking
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=AccountsOpneningDB


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=demo.psccs@gmail.com
spring.mail.password=lhoarrnsupvizqzx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

